name: Test package

on:
  workflow_dispatch:
  push:
    branches:
      - gha

jobs:
  test:
    runs-on: gha-runners-delib-py2
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7"]
        plone-version: ["4.3"]
        experimental: [false]
    services:
      soffice:
        image: harbor.imio.be/common/libreoffice:7.3
        ports:
          - 2002:2002
        volumes:
          - /tmp:/tmp
          - /var/tmp:/var/tmp
        credentials:
          username: ${{ secrets.COMMON_HARBOR_USERNAME }}
          password: ${{ secrets.COMMON_HARBOR_PASSWORD }}
    steps:
      - name: Needed for local development
        if: ${{ env.ACT }}
        run: echo /home/runner/externals/node20/bin >> $GITHUB_PATH
      - name: Run tests
        uses: IMIO/gha/plone-package-test-notify@v4
        env:
          cache-name: cache-eggs
        with:
          CACHE_KEY: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}
          #TEST_COMMAND: OO_SERVER=loffice OO_PORT=2002 bin/testmc -s Products.PloneMeeting --layer=\!ROBOT --test=\!\(testSetup\|testPerf\)
          TEST_COMMAND: echo "No tests to run"
          INSTALL_DEPENDENCIES_COMMANDS: |
            sudo pip install -r requirements-tests.txt
          MATTERMOST_WEBHOOK_URL: ${{ secrets.DELIB_MATTERMOST_WEBHOOK_URL }}