name: Dispatch tests to Products.Meeting*

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - gha
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dispatch-tests:
    runs-on: gha-runners-delib-py2
    strategy:
      matrix:
        repository:
          - Products.MeetingBEP
          - Products.MeetingCommunes
          - Products.MeetingCharleroi
          - Products.MeetingCPASLalouviere
          - Products.MeetingLalouviere
          - Products.MeetingLiege
          - Products.MeetingMons
          - Products.MeetingNamur
          - Products.MeetingPROVHainaut
          - Products.MeetingSeraing
    if: ${{ !github.event_name == 'pull_request' || !github.event.pull_request.draft }}
    steps:
      - name: Needed for local development
        if: ${{ env.ACT }}
        run: echo /home/runner/externals/node20/bin >> $GITHUB_PATH
        shell: bash
      - name: Dispatch test to ${{ matrix.repository }}
        uses: IMIO/gha/repository-dispatch-notify@main
        with:
          REPOSITORY: ${{ matrix.repository }}
          REPOSITORY_OWNER: IMIO
          GIT_REFERENCE: gha
          WORKFLOW_FILENAME: tests.yml
          APP_ID: ${{ vars.APPS_ID_IMIO_GHA }}
          APP_PRIVATE_KEY: ${{ secrets.APPS_PRIVATE_KEY_IMIO_GHA }}